name: spaceship-titanic-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - xgboost=2.0.3
  - jupyter=1.0.0